# Makefile — single source of truth for lint/format. Humans and CI run the SAME
# commands, so "passes locally" means "passes in CI".
#
# Scope: only repo-owned files. `core/` is a vendored git-subtree from
# dotfiles-core and is linted in THAT repo's CI — reformatting it here would
# fight the subtree. A non-blocking `core-advisory` target surfaces core/ findings
# without gating. See README "Development".
#
# Quick start:  make lint   (run everything)   |   make fmt   (auto-format)

SHELL := bash
.DEFAULT_GOAL := help

# Repo-owned bash scripts: every *.sh outside the vendored core/ subtree, plus
# sketchybar/sketchybarrc — a bash entry point with NO .sh extension (sketchybar
# requires that exact filename), so the glob would miss it. Append it explicitly
# so shellcheck/shfmt/syntax cover it like any other repo-owned script.
SH_FILES := $(shell find . -name '*.sh' -not -path './core/*' -not -path './.git/*' | sort) sketchybar/sketchybarrc
SHFMT_FLAGS := -i 2

# Repo-owned zsh modules. These are the real behavioral surface of this repo, yet
# the .sh-only globs above never reach them (the entry files have NO extension).
# `zsh -n` parses each so a broken edit can't ship green. core/ zsh is gated in
# dotfiles-core's own CI.
ZSH_FILES := zsh/zshenv zsh/zprofile zsh/zshrc os/macos.zsh

.PHONY: help lint fmt fmt-check shellcheck syntax zsh-syntax check core-advisory \
        tools test test-repo test-all bench bootstrap bootstrap-dry doctor sync-core \
        core-audit verify-core core-lock brew-check

help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## ' $(MAKEFILE_LIST) \
	  | awk 'BEGIN{FS=":.*?## "}{printf "  \033[36m%-15s\033[0m %s\n",$$1,$$2}'

lint: shellcheck fmt-check syntax zsh-syntax ## Run all gating checks (shellcheck + format + bash/zsh syntax)

shellcheck: ## Static analysis of repo-owned bash
	@shellcheck $(SH_FILES)

fmt-check: ## Verify formatting without writing (CI uses this)
	@shfmt $(SHFMT_FLAGS) -d $(SH_FILES)

fmt: ## Auto-format repo-owned bash in place
	@shfmt $(SHFMT_FLAGS) -w $(SH_FILES)

syntax: ## `bash -n` syntax gate on every repo-owned script
	@for f in $(SH_FILES); do bash -n "$$f" || exit 1; done
	@echo "syntax ok:"; printf '  %s\n' $(SH_FILES)

zsh-syntax: ## `zsh -n` syntax gate on repo-owned zsh modules (skips if zsh absent)
	@command -v zsh >/dev/null 2>&1 || { echo "  skip zsh-syntax (zsh not installed)"; exit 0; }
	@for f in $(ZSH_FILES); do zsh -n "$$f" || exit 1; done
	@echo "zsh syntax ok:"; printf '  %s\n' $(ZSH_FILES)

core-advisory: ## Non-blocking shellcheck over vendored core/ (fixes land upstream)
	@shellcheck $$(find core -name '*.sh') || \
	  echo "(advisory) core/ findings above are fixed upstream in dotfiles-core"

core-audit: ## Gate the vendored Core subtree with its OWN audit (manifest/exec-bits/syntax/config drift a subtree pull can introduce)
	@cd core && ./scripts/audit-core.sh --quiet

verify-core: ## Assert vendored core/ is byte-for-byte upstream @ the recorded subtree-split (catches hand-edits + orphans the dir-level manifest misses)
	@./test/verify-core.sh

# The output MUST stay byte-identical to what dotfiles-core's sync-core.sh writes, because
# that is what every other consumer reads: core-integrity.sh parses `core_tag`, and
# fleet-drift.sh reports `core_version`/`core_sha`/`core_tag` per repo. This recipe used to
# emit a DIFFERENT header and drop `core_tag` entirely — so running it (which the sync-core
# help text below tells you to do after a manual pull) silently downgraded the lock and
# produced a spurious diff against the automated writer.
#
# `core_branch` legitimately holds a SHA: the fan-out sets CORE_BRANCH=<target sha> so the
# lock records exactly what was vendored, not a moving branch name. Preserved from the
# existing lock unless CORE_BRANCH overrides it.
#
# `core_tag` is emitted as v<core.version> when core.version is a well-formed X.Y.Z, which
# is Core's release-tag convention. Vendoring an UNTAGGED Core (a pre-release SHA) is the
# one case this cannot know about — drop the line by hand there, matching sync-core.sh,
# which only emits it once Core actually carries a tag.
core-lock: ## Regenerate core.lock from the vendored subtree-split (after a MANUAL subtree pull; CORE_BRANCH overrides the recorded branch; sync-core writes it automatically)
	@split="$$(git log --grep='git-subtree-dir: core' -n1 --format='%b' 2>/dev/null \
	  | sed -n 's/^[[:space:]]*git-subtree-split:[[:space:]]*//p' | head -n1)"; \
	 [ -n "$$split" ] || { echo "  core-lock: no git-subtree-split marker (not a subtree checkout?)" >&2; exit 1; }; \
	 ver="$$(tr -d '[:space:]' < core/core.version 2>/dev/null || echo unknown)"; \
	 branch="$${CORE_BRANCH:-$$(sed -n 's/^core_branch=//p' core.lock 2>/dev/null | head -n1)}"; \
	 branch="$${branch:-main}"; \
	 { echo "# GENERATED by dotfiles-core sync-core.sh — vendored Core provenance (B1)."; \
	   echo "# Regenerate after a manual 'git subtree pull' with: make core-lock"; \
	   echo "core_version=$$ver"; echo "core_sha=$$split"; echo "core_branch=$$branch"; \
	   case "$$ver" in [0-9]*.[0-9]*.[0-9]*) echo "core_tag=v$$ver" ;; esac; } > core.lock; \
	 echo "  wrote core.lock → $$(echo "$$split" | cut -c1-12) (v$$ver, $$branch) — review + commit it"

test: ## Run the vendored Core regression harness (self-skips without zsh)
	@cd core && ./scripts/test-core.sh

test-repo: ## Run THIS repo's behavioral tests (bootstrap.sh, zsh loader, defaults.sh)
	@./test/test-repo.sh

test-all: test-repo test ## Run repo-owned tests + the vendored Core harness

bench: ## Measure Core shell-startup cost (set CORE_BENCH_BUDGET_MS to gate)
	@cd core && ./scripts/bench-core.sh

brew-check: ## Verify every Brewfile formula/cask is installed (the reproducibility gate; run on macOS)
	@command -v brew >/dev/null 2>&1 || { echo "  brew not found — run this on macOS"; exit 1; }
	@brew bundle check --file=Brewfile --verbose

bootstrap: ## Install: symlinks + Homebrew + brew bundle (macOS)
	@./bootstrap.sh

bootstrap-dry: ## Preview the installer plan (symlinks); change nothing
	@./bootstrap.sh --links-only --dry-run

doctor: ## Show what bootstrap would change + verify the lint toolchain
	@./bootstrap.sh --links-only --dry-run || true
	@$(MAKE) -s tools || true

sync-core: ## Reminder: how the vendored Core subtree gets updated
	@echo "  Normally nothing to run: a dotfiles-core release opens a sync PR here"
	@echo "  automatically (sync-fanout.yml). Merge it, then:"
	@echo "    ./bootstrap.sh --links-only   # re-wire any new/changed Core files"
	@echo "    make test                     # prove the new Core still loads"
	@echo "  By hand, take the RELEASED tag (never main) and regenerate the lock,"
	@echo "  or core-integrity reports the fresh subtree as TAMPERED:"
	@echo "    git subtree pull --prefix=core <remote>/dotfiles-core refs/tags/v4 --squash"
	@echo "    make core-lock                # sync-core.sh does this for you upstream"

check: lint ## Alias for `lint`

tools: ## Verify the lint toolchain is installed
	@for t in shellcheck shfmt; do \
	  command -v $$t >/dev/null && echo "  ok  $$t" \
	    || { echo "  MISSING $$t — run: brew bundle (or see Brewfile 'Dev: lint & format')"; exit 1; }; \
	done
